<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>org.g14.$(MSBuildProjectName)</AssemblyName>
        <RootNamespace>org.g14.$(MSBuildProjectName)</RootNamespace>
    </PropertyGroup>

</Project>
